config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
  end

namespace :dashboard do
  root 'dashboard#index'
end

  resources :users

  resources :posts do
    collection do
      get 'encontrados', to: 'posts#found', as: :found
      get 'perdidos',    to: 'posts#lost', as: :lost
      get 'adopciones',  to: 'posts#adoption', as: :adoption
    end

    member do
      get 'geo'
    end
  end



  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base

	attr_accessor :image
	belongs_to :user

	before_validation :set_defaults, on: :create

	validates :title, :state, :contact, :description, presence: true
	validates :image, presence: true if Rails.env.production?

	after_validation :geocode, :if => :location_changed?

	mount_uploader :image, ImageUploader
	geocoded_by :location

	scope :found, 		-> { where(state: 'found') }
	scope :lost,			-> { where(state: 'lost') }
	scope :adoption,	-> { where(state: 'adoption') }

	def active?
		self.status == 'active'
	end

	def closed?
		self.status == 'closed'
	end

	private

	def set_defaults
      self.status = 'active'
    end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts

	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |field| field.permit(:name, :nick, :email, :password, :password_confirmation) }
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
	layout "dashboard"

	before_action :require_admin
	def require_admin
		redirect_to login_path unless current_user.admin
	end

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < Dashboard::BaseController
	layout "dashboard"

	def index
		@user = User.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :geolocation]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @found    = Post.found.order(created_at: :desc).limit(3)
    @lost     = Post.lost.order(created_at: :desc).limit(3)
    @adoption = Post.adoption.order(created_at: :desc).limit(3)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)
      if @post.save
        flash[:success] = "Esto fue un exito."
        render :show
      else
        flash[:error] = @post.errors.messages
        render :new
    end
  end

  def update
      if @post.update(post_params)
        flash[:success] = "Esto fue un exito."
        render :show
      else
        flash[:error] = "Paa, drama."
        render :edit
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def found
    @founds = Post.found.page(params[:page]).order(created_at: :desc)
  end

  def lost
    @losts = Post.lost.page(params[:page]).order(created_at: :desc)
  end

  def adoption
    @adoptions = Post.adoption.page(params[:page]).order(created_at: :desc)
  end

  def geo
    @post = Post.find params[:id]

    @geojson = {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          @post.latitude,
          @post.longitude
        ]
      },
      properties: {
        title: @post.title,
        description: @post.location,
        :"marker-color" => "#00607d",
        :"marker-symbol" => "circle",
        :"marker-size" => "medium"
      }
    }.to_json

    render json: @geojson
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :state, :description, :image, :location, :status, :contact, :animal_type, :age, :breed, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
  	authenticate_user!
  	@user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/dashboard/index.html.haml
- @user.each do |user|
  = user.name

app/views/layouts/_footer.html.haml
.footer
  .container
    .row
      .col-md-1
        = link_to "Publicar", new_post_path, class: 'btn btn-primary'
      %a{:href => "https://twitter.com/peteretescom"}
        %img{:alt => "twitter", src: asset_path('social-32-twitter.png')}/
      %a{:href => "https://www.facebook.com/peteretespeteretes"}
        %img{:alt => "facebook", src: asset_path('social-31-facebook.png')}/
      %span.social.social-facebook
      .col-md-8
        %ul
          %li= link_to "El Proyecto", page_path('about')
          \-
          %li= link_to "Colabora", page_path('collaborates')
          \-
          %li= link_to "Contacto", page_path('contact')
          / <li>link_to &amp;quot;Manifiesto&amp;quot;, page_path('manifesto') </li>

app/views/layouts/_header.html.haml
- if user_signed_in?
  = render 'layouts/signed_in_header'
- else
  = render 'layouts/signed_out_header'

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/_signed_in_dashboard.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <h1 class="logo"><%= link_to image_tag('http://res.cloudinary.com/dqyonjr6e/image/upload/v1420592569/logo_2x_gu1jun.png'), root_path, class: "logo" %></h1>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Perfil <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to current_user.name, current_user %></li>
            <li class="divider"></li>
            <li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_signed_in_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %h1.logo= link_to image_tag('http://res.cloudinary.com/dqyonjr6e/image/upload/v1420592569/logo_2x_gu1jun.png'), root_path, class: "logo"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Encontrados", found_posts_path
        %li= link_to "Perdidos", lost_posts_path
        %li= link_to "En Adopción", adoption_posts_path
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown{:role => "presentation"}
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Perfil
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li= link_to current_user.name, current_user
            %li= link_to 'Editar Perfil', edit_user_registration_path
            %li.divider
            %li= link_to "Salir", destroy_user_session_path, :method => :delete
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/_signed_out_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %h1.logo= link_to image_tag('http://res.cloudinary.com/dqyonjr6e/image/upload/v1420592569/logo_2x_gu1jun.png'), root_path, class: "logo"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Encontrados", found_posts_path
        %li= link_to "Perdidos", lost_posts_path
        %li= link_to "En Adopción", adoption_posts_path
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Entra", new_user_session_path
        %li= link_to "Registrate", new_user_registration_path
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Peteretes - Encuentra y ayuda a encontrar mascotas perdidas.
    %meta{:content => "width=device-width", :name => "viewport"}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.css'

    = javascript_include_tag 'https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.js'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'google_analytics'

    = csrf_meta_tags

  %body
    = render 'layouts/header'

    .container
      = render 'layouts/messages'
      = yield

    = render 'layouts/footer'

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peteretes - Dashboard.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
</head>

<body>
  <%= render 'layouts/signed_in_dashboard' %>


  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title Peteretes - Dashboard.
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width", :name => "viewport"}
  %body
    .container
      = render 'layouts/messages'
      = yield
    = render 'layouts/footer'

app/views/pages/about.html.erb
<h1>Historia del proyecto</h1>
<p>Es más que común ver tweets de personas pidiendo RT´s a famosos para ayudar con difusión para encontrar sus mascotas perdidas, como también es común ver publicaciones de personas que encontraron algún perrito perdido y están buscando a sus dueños. Me pasa todos los días. Siempre que veo esto, me pregunto qué pasaría si hubiese un lugar donde todos sepan que tienen que visitar, cuando pasan estas cosas. Como ir a “objetos perdidos” en informaciones de algún mall. </p>

<h3>El problema</h3>


<p>Las publicaciones de animalitos perdidos/encontrados andan dando vuelta por redes sociales, sin un hashtag en común, sin un lugar especifico donde buscar. Es super dificil llegar a la persona que estamos buscando, es cuestion de suerte dar en el clavo.</p>

<h3>La solución</h3>


<p>Después de pensarlo harto, me hice un tiempo y programé esta pequeña página donde la gente puede publicar su mascota perdida, publicar que encontró una y además, publicar si está dando en adopción. Son estas tres categorias básicas.</p>

<p>La página es super simple, solo hay que llenar un formulario y el aviso se publica. Puedes poner una imagen, una forma de contacto, la ubicación de la publicación (ej: mi perrito se perdió en la calle Av Siempre Viva 899 ), la descripción, raza y listo. Quise hacerlo más simple, pero creo que entre más datos se pidan, más fácil encontrar a sus dueños será.</p>

<p>El nombre es por Pet + RT´s (pet + eretes, boom). No tiene mucha ciencia. Aparte tengo un amigo al que le digo peteretes, un homenaje a él.</p>

<p>Voy a ir arreglando y añadiendo cosas con el pasar de los días, por ahora es super básico, pero sirve para lo que pensé inicialmente. Si quieres ayudar de cualquier forma, bienvenido seas, ser hermoso.</p>

<p>Un gran agradecimiento a Claudio Castillo, que donó gentilmente este simple pero hermoso logo y me ayudó a ponerlo en el header.</p>

app/views/pages/collaborates.html.erb
<h1>Colabora</h1>

<p>Si quieres ayudar de cualquier forma, te lo agradeceré de corazón.</p>
<p>Cualquier ayuda es bienvenida, pero estaré especialmente agradecido quieres hermosear el sitio, ayuadar con el SEO, con redes sociales, con lo que sea. Hasta un tweet buena onda nos basta.</p>

<p>Mi correo es <a href="mailto:lopezrivasdaniel@gmail.com">lopezrivasdaniel@gmail.com. </a>Está prendido 24/7.</p>

app/views/pages/contact.html.erb
<h1>Contacto</h1>

<p>Cualquier duda o pregunta, mi correo es <a href="mailto:lopezrivasdaniel@gmail.com">lopezrivasdaniel@gmail.com.</a></p>

app/views/pages/manifesto.html.erb
<h1>Manifesto</h1>

app/views/posts/_action_links.html.haml
%h5.text-center
  - if user_signed_in? and current_user.id == @post.user.id
    = link_to 'Editar', edit_post_path(@post)
    |
    = link_to 'Borrar', @post, method: :delete, data: { confirm: "Seguro?"}
    |
    = link_to 'Atrás', posts_path
  - else
    = link_to 'Atrás', posts_path

app/views/posts/_contact_info.html.haml
.panel.panel-default
  .panel-heading
    Información de contacto
  .panel-body
    %p= "Nombre: #{@post.user.name}"
    %p= "Contacto: #{@post.contact}"

app/views/posts/_description.html.haml
.panel.panel-default
  .panel-heading Descripción
  .panel-body
    %h3
      = @post.title
    %p
      %strong ¿Qué animalito es?
      = @post.animal_type
    %p
      %strong Raza:
      = @post.breed
    %p
      %strong Edad:
      = @post.age
    %p
      %strong ¿Dónde?
      = @post.location
    %p= @post.description

app/views/posts/_form.html.haml
.container
  .panel.panel-default.col-md-8
    .panel-body
      = simple_form_for @post, :defaults => {:required => false}, :html => {:multipart => true} do |f|
        = f.input :title, label: 'Titulo'
        .btn-group
          = f.input :state, as: :radio_buttons, collection: [["Encontrado", "found"], ["Perdido", "lost"], |
            ["En Adopción", "adoption"]]                                                                   |
        = f.input :location, label: 'Ubicación'
        = f.label 'Imagen'
        = f.file_field :image, class: 'btn btn-default'
        = f.input :contact, label: 'Contacto'
        .btn-group
          = f.input :animal_type, label: "Tipo de mascota", as: :radio_buttons, collection: [["Perrito", "dog"], ["Gatito", "cat"]]
        = f.input :breed, label: 'Raza'
        = f.input :age, label: 'Edad aproximada'
        = f.input :description, label: 'Descripción'
        = f.button :submit , :value => "Publicar"

app/views/posts/_map.html.haml
#map.dark

:javascript
  $(document).ready(function(){
    $("#map").css("height", '400')
    L.mapbox.accessToken = 'pk.eyJ1IjoicGV0ZXJldGVzIiwiYSI6ImEyYUxxRTAifQ.ZK97j8BA0SXOaQ16Mri2oA';

    var latlng = ["#{@post.latitude}", "#{@post.longitude}"]
    //var circleMarker = L.circleMarker(latlng).setRadius(180);

    var map = L.mapbox.map('map', 'peteretes.kokmenp1')
      .setView(latlng, 15);

    L.marker(latlng, {
      icon: L.mapbox.marker.icon({
        'marker-size': 'large',
        'marker-symbol': 'dog-park',
        'marker-color': '#fa0'
      })
    }).addTo(map);
  });

app/views/posts/_photo.html.haml
- if @post.image.blank?
  = image_tag "http://placehold.it/317x317", class: "img-responsive img-thumbnail"
- else
  = image_tag @post.image.url, class: "img-responsive img-thumbnail"

app/views/posts/_single_post.html.haml
- posts.each do |post|
  - if post.active?
    .thumbnail
      %h3= post.title

      - if post.image.blank?
        = image_tag "http://placehold.it/317x317", class: "img-responsive img-thumbnail"
      - else
        = link_to image_tag(post.image_url.to_s), post_path(post), class: "img-responsive img-thumbnail"

      .caption
        %p= truncate post.description, length: 140
        = link_to 'Ver', post, class: "btn btn-default"

    = link_to 'Ver todos', eval("#{post.state}_posts_path")

app/views/posts/adoption.html.haml
%h1 Encontrados
.row
  .col-xs-12.col-md-8
    - @adoptions.each do |post|
      - if post.active?
        .thumbnail
          %h3= post.title
          - if post.image.blank?
            = image_tag "http://placehold.it/317x317", class: "img-responsive img-thumbnail"
          - else
            = link_to image_tag(post.image_url.to_s), post_path(post), class: "img-responsive img-thumbnail"

          .caption
            %p= truncate post.description, length: 140
            = link_to 'Ver', post, class: "btn btn-default"
  .col-xs-6.col-md-4
= paginate @adoptions, :theme => 'twitter-bootstrap-3'

app/views/posts/edit.html.haml
%h1 Editing post
.container
  .panel.panel-default.col-md-8
    .panel-body
      = simple_form_for @post, :defaults => {:required => false}, :html => {:multipart => true} do |f|
        = f.input :title, label: 'Titulo'
        .btn-group
          = f.input :state, as: :radio_buttons, collection: [["Encontrado", "found"], ["Perdido", "lost"], |
            ["En Adopción", "adoption"]]                                                                   |
        = f.input :location, label: 'Ubicación'
        = f.label 'Imagen'
        = f.file_field :image, class: 'btn btn-default'
        = f.input :contact, label: 'Contacto'
        .btn-group
          = f.input :animal_type, label: "Tipo de mascota", as: :radio_buttons, collection: [["Perrito", "dog"], ["Gatito", "cat"]]
        = f.input :breed, label: 'Raza'
        = f.input :age, label: 'Edad aproximada'
        = f.input :description, label: 'Descripción'
        = f.input :status, collection: ['active', 'closed']
        = f.button :submit , :value => "Publicar"
= link_to 'Mostrar', @post
|
\#{link_to 'Atrás', posts_path}

app/views/posts/found.html.haml
%h1 Encontrados
.row
  .col-xs-12.col-md-8
    - @founds.each do |post|
      - if post.active?
        .thumbnail
          %h3= post.title
          - if post.image.blank?
            = image_tag "http://placehold.it/317x317", class: "img-responsive img-thumbnail"
          - else
            = link_to image_tag(post.image_url.to_s), post_path(post), class: "img-responsive img-thumbnail"

          .caption
            %p= truncate post.description, length: 140
            = link_to 'Ver', post, class: "btn btn-default"
  .col-xs-6.col-md-4
= paginate @founds, :theme => 'twitter-bootstrap-3'

app/views/posts/index.html.haml
.jumbotron
  .row
    .intro
      .col-md-12
        %h1 ¡Nos gustan los animales!
        %p.lead ¿Perdiste tu mascota? ¿Encontraste la mascota de alguien? ¿Quieres dar un animalito en adopción o quieres adoptar?
        %p.lead ¡Este es tu lugar!
        = link_to "Publicar", new_post_path, class: "btn btn-primary btn-lg"
        %hr

.row.ficha
  .col-sm-6.col-md-4
    %h2 Encontrados
    = render partial: "single_post", locals: { posts: @found }

  .col-sm-6.col-md-4
    %h2 Perdidos
    = render partial: "single_post", locals: { posts: @lost }

  .col-sm-6.col-md-4
    %h2 En Adopcion
    = render partial: "single_post", locals: { posts: @adoption }

app/views/posts/lost.html.haml
%h1 Encontrados
.row
  .col-xs-12.col-md-8
    - @losts.each do |post|
      - if post.active?
        .thumbnail
          %h3= post.title
          - if post.image.blank?
            = image_tag "http://placehold.it/317x317", class: "img-responsive img-thumbnail"
          - else
            = link_to image_tag(post.image_url.to_s), post_path(post), class: "img-responsive img-thumbnail"

          .caption
            %p= truncate post.description, length: 140
            = link_to 'Ver', post, class: "btn btn-default"
  .col-xs-6.col-md-4
= paginate @losts, :theme => 'twitter-bootstrap-3'

app/views/posts/new.html.haml
%h1 Nueva publicación
= render 'form'
= link_to 'Atrás', posts_path

app/views/posts/show.html.haml
.container
  %p#notice
    = notice

  .panel.panel-default
    .panel-body
      .title
        - if @post.state == 'lost'
          %h1.center-text Perdido
        - elsif @post.state == 'found'
          %h1.text-center Encontrado
        - elsif @post.state == 'adoption'
          %h1 En Adopción

        = render partial: "action_links"
        %hr

      .row
        .col-md-4
          = render partial: "photo"
        .col-md-6.col-md-offset-1
          = render partial: "description"

      %br

      .row
        .col-md-4
          = render partial: "contact_info"
        .col-md-6.col-md-offset-1{ style: "padding-bottom: 50px;" }
          = render partial: "map"

app/views/users/show.html.haml
.panel.panel-default
  .panel-heading
    Los animalitos que tienes publicados
  .panel-body
    %table.table.table-hover
      %thead
        %tr
          %th
            %p Título
          %th
            %p Descripción
          %th
            %p Acciones
          %th
          %th
      - @user.posts.each do |post|
        %tbody
          %tr
            %th= post.title
            %td= post.description
            - if post.user.id == current_user.id
              %td= link_to "Editar", edit_post_path(post)
              %td= link_to "Ver", post_path(post)
              %td= link_to "Borrar", post, method: :delete, data: {confirm: "¿Seguro?"}
            - else